// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sistema_Ferreteria.Data;

#nullable disable

namespace Sistema_Ferreteria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sistema_Ferreteria.Models.Clientes.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<decimal>("DescuentoPorcentaje")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("DescuentoPorcentaje");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LimiteCredito");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NumeroDocumento");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("SaldoActual");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("TipoDocumento");

                    b.HasKey("IdCliente");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.Compra", b =>
                {
                    b.Property<long>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdCompra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdCompra"));

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DescuentoMonto");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaAnulacion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaVencimiento");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("integer")
                        .HasColumnName("IdProveedor");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<decimal>("ImpuestoMonto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ImpuestoMonto");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MotivoAnulacion");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NumeroFactura");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioAnulacion")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioAnulacion");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioAnulacion");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.DetalleCompra", b =>
                {
                    b.Property<long>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdDetalleCompra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdDetalleCompra"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadBase")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("CantidadBase");

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DescuentoMonto");

                    b.Property<long>("IdCompra")
                        .HasColumnType("bigint")
                        .HasColumnName("IdCompra");

                    b.Property<int>("IdPresentacion")
                        .HasColumnType("integer")
                        .HasColumnName("IdPresentacion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioUnitario");

                    b.HasKey("IdDetalleCompra");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdPresentacion");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetalleCompra");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.PagoCompra", b =>
                {
                    b.Property<long>("IdPagoCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdPagoCompra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPagoCompra"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaPago");

                    b.Property<long>("IdCompra")
                        .HasColumnType("bigint")
                        .HasColumnName("IdCompra");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NumeroComprobante");

                    b.HasKey("IdPagoCompra");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdUsuario");

                    b.ToTable("PagosCompra");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Configuracion.Configuracion", b =>
                {
                    b.Property<int>("IdConfig")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdConfig");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConfig"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Modulo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("IdConfig");

                    b.ToTable("Configuracion");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdCategoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.MovimientoInventario", b =>
                {
                    b.Property<long>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdMovimiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdMovimiento"));

                    b.Property<decimal>("CantidadBase")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("CantidadBase");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<int?>("IdReferencia")
                        .HasColumnType("integer")
                        .HasColumnName("IdReferencia");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TipoMovimiento");

                    b.Property<string>("TipoReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("TipoReferencia");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MovimientosInventario");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Presentacion", b =>
                {
                    b.Property<int>("IdPresentacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdPresentacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresentacion"));

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CodigoBarras");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("EsPrincipal");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<decimal>("FactorConversion")
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("FactorConversion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<int>("IdUnidadPresentacion")
                        .HasColumnType("integer")
                        .HasColumnName("IdUnidadPresentacion");

                    b.Property<string>("NombrePresentacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("NombrePresentacion");

                    b.Property<decimal?>("PrecioCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioCompra");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioVenta");

                    b.HasKey("IdPresentacion");

                    b.HasIndex("IdUnidadPresentacion");

                    b.HasIndex("IdProducto", "NombrePresentacion")
                        .IsUnique();

                    b.ToTable("Presentaciones");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("CodigoBarras");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("integer")
                        .HasColumnName("IdCategoria");

                    b.Property<int>("IdUnidadBase")
                        .HasColumnType("integer")
                        .HasColumnName("IdUnidadBase");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("PrecioBaseCompra")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioBaseCompra");

                    b.Property<decimal?>("PrecioBaseVenta")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioBaseVenta");

                    b.Property<decimal>("StockBase")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("StockBase");

                    b.Property<decimal>("StockMinimo")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("StockMinimo");

                    b.HasKey("IdProducto");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUnidadBase");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdUnidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdUnidad");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Proveedores.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdProveedor");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("ContactoNombre")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ContactoNombre");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NumeroDocumento");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("PlazoPago")
                        .HasColumnType("integer")
                        .HasColumnName("PlazoPago");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("TipoDocumento");

                    b.HasKey("IdProveedor");

                    b.HasIndex("TipoDocumento", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Auditoria", b =>
                {
                    b.Property<long>("IdAuditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdAuditoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdAuditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Entidad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdEntidad")
                        .HasColumnType("integer")
                        .HasColumnName("IdEntidad");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("IpAddress");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdAuditoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdPermiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdRol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.RolPermiso", b =>
                {
                    b.Property<int>("IdRolPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdRolPermiso");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRolPermiso"));

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("IdPermiso");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("IdRol");

                    b.HasKey("IdRolPermiso");

                    b.HasIndex("IdPermiso");

                    b.HasIndex("IdRol", "IdPermiso")
                        .IsUnique();

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("ContraseñaHash");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaCreacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("IdUsuario");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuarioRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuarioRol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuarioRol"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaAsignacion");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("IdRol");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.HasKey("IdUsuarioRol");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdUsuario", "IdRol")
                        .IsUnique();

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.DetalleVenta", b =>
                {
                    b.Property<long>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdDetalleVenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdDetalleVenta"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CantidadBase")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnName("CantidadBase");

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DescuentoMonto");

                    b.Property<int>("IdPresentacion")
                        .HasColumnType("integer")
                        .HasColumnName("IdPresentacion");

                    b.Property<int>("IdProducto")
                        .HasColumnType("integer")
                        .HasColumnName("IdProducto");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("IdVenta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PrecioUnitario");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("IdPresentacion");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.PagoVenta", b =>
                {
                    b.Property<long>("IdPagoVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdPagoVenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPagoVenta"));

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaPago");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<long>("IdVenta")
                        .HasColumnType("bigint")
                        .HasColumnName("IdVenta");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("MetodoPago");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("NumeroComprobante");

                    b.HasKey("IdPagoVenta");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdVenta");

                    b.ToTable("PagosVenta");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.Venta", b =>
                {
                    b.Property<long>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("IdVenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdVenta"));

                    b.Property<decimal>("DescuentoMonto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DescuentoMonto");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaAnulacion");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaVencimiento");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("IdCliente");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("IdUsuario");

                    b.Property<decimal>("ImpuestoMonto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ImpuestoMonto");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("MotivoAnulacion");

                    b.Property<string>("NumeroFactura")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("NumeroFactura");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoPago")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("TipoPago");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UsuarioAnulacion")
                        .HasColumnType("integer")
                        .HasColumnName("UsuarioAnulacion");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("UsuarioAnulacion");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.Compra", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Proveedores.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "UsuarioAnulacionNavigation")
                        .WithMany()
                        .HasForeignKey("UsuarioAnulacion");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacionNavigation");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.DetalleCompra", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Compras.Compra", "Compra")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Presentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("IdPresentacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Presentacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.PagoCompra", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Compras.Compra", "Compra")
                        .WithMany("PagosCompra")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.MovimientoInventario", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Producto", "Producto")
                        .WithMany("MovimientosInventario")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Presentacion", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Producto", "Producto")
                        .WithMany("Presentaciones")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Inventario.UnidadMedida", "UnidadPresentacion")
                        .WithMany("Presentaciones")
                        .HasForeignKey("IdUnidadPresentacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("UnidadPresentacion");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Producto", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Inventario.UnidadMedida", "UnidadBase")
                        .WithMany("Productos")
                        .HasForeignKey("IdUnidadBase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadBase");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Auditoria", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("Auditorias")
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.RolPermiso", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.UsuarioRol", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.DetalleVenta", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Presentacion", "Presentacion")
                        .WithMany()
                        .HasForeignKey("IdPresentacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Inventario.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Ventas.Venta", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Presentacion");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.PagoVenta", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Ventas.Venta", "Venta")
                        .WithMany("PagosVenta")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.Venta", b =>
                {
                    b.HasOne("Sistema_Ferreteria.Models.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente");

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sistema_Ferreteria.Models.Seguridad.Usuario", "UsuarioAnulacionNavigation")
                        .WithMany()
                        .HasForeignKey("UsuarioAnulacion");

                    b.Navigation("Cliente");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioAnulacionNavigation");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Compras.Compra", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("PagosCompra");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.Producto", b =>
                {
                    b.Navigation("MovimientosInventario");

                    b.Navigation("Presentaciones");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Inventario.UnidadMedida", b =>
                {
                    b.Navigation("Presentaciones");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Seguridad.Usuario", b =>
                {
                    b.Navigation("Auditorias");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Sistema_Ferreteria.Models.Ventas.Venta", b =>
                {
                    b.Navigation("DetalleVentas");

                    b.Navigation("PagosVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
